---
name: Release

on:
  push:
    branches: [ main, master ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install yamllint ansible-lint ansible

      - name: Run tests before release
        run: |
          yamllint .
          ansible-lint
          ansible-playbook tests/test.yml --syntax-check

      - name: Generate changelog and tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: v
          append_to_pre_release_tag: ""

      - name: Create GitHub Release
        if: steps.tag_version.outputs.new_tag
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: |
            ## Changes in this Release
            ${{ steps.tag_version.outputs.changelog }}
            
            ## Installation
            
            ```bash
            ansible-galaxy install alemuro.mosquitto
            ```
            
            ## Usage
            
            ```yaml
            - hosts: pi
              roles:
                - { role: alemuro.mosquitto }
            ```
          draft: false
          prerelease: false

      - name: Publish to Ansible Galaxy
        if: steps.tag_version.outputs.new_tag
        run: |
          echo "New release created: ${{ steps.tag_version.outputs.new_tag }}"
          echo "Consider publishing to Ansible Galaxy manually if desired"